name: DreamDisplays
version: '${version}'
authors: [ arsmotorin, INotSleep, Toffikk ]
description: 'Plugin for the Dream Displays mod.'
main: com.dreamdisplays.Main
api-version: '1.21'
folia-supported: true
permissions:
  dreamdisplays.create:
    default: true
  dreamdisplays.video:
    default: true
